### ISSUE TITLE
Sending Monday meeting room booking reminders on a Friday

### ISSUE THREAD

**Issue by emmabeynon** [Wynndow/meeting_room_project#30]
I had a meeting room booking for Monday morning, and only saw the reminder email on that day.  It would be cool to get Monday meeting room booking reminders sent on a Friday so that people see them in plenty of time and can change their bookings if necessary 👍

**Comment by Wynndow** [comment]
I totally fixed it! Probably! We'll have to wait until next Friday to see.

Thanks!

**Comment by emmabeynon** [comment]
🎉
